<a href="https://colab.research.google.com/github/leiyi-ihb/ColabPractics/blob/main/B_practices/keras_example03_MNIST%E6%95%B0%E6%8D%AE%E9%9B%86%E5%88%86%E7%B1%BB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD 

In [2]:
#输入数据
(x_train, y_train), (x_test, y_test)=mnist.load_data()
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

11490434/11490434 [==============================] - 0s 0us/step
(60000, 28, 28) (60000,)
(10000, 28, 28) (10000,)


In [5]:
from os import XATTR_CREATE
# 将(60000, 28, 28)转为(60000, 784)，这里的784其实就是28*28【我的理解应该是降维处理】
x_train = x_train.reshape(x_train.shape[0], -1) #行数就是取原来的60000，列数取-1表示不确定，由程序自己判断。 
# x_train = x_train.reshape(x_train.shape[0], 784) #跟上面一样的结果
x_test = x_test.reshape(x_test.shape[0], -1)
print(x_train.shape, len(x_train[0])) #可以发现，数据就变成一个60000行，784列的数据了
# print(x_train[0])

#需要对数据做个归一化
print(x_train.max()) 
x_train = x_train/255 #知道这里为什么除的是255吗？最大值为255
# print(x_train[0])
print(x_train.max())

x_test = x_test/255

# 转换label为one hot形式
from keras.utils import np_utils
print(y_train[0])
y_train = np_utils.to_categorical(y_train, num_classes=10) #这里为啥分为10个类没有讲清楚
y_test = np_utils.to_categorical(y_test, num_classes=10) #这里为啥分为10个类没有讲清楚
print(y_train[0])

(60000, 784) 784
1.0
0.00392156862745098
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
60000


**Note:**知道为什么要将(60000, 28, 28)转换为(60000, 784)吗？其实是Dense层输入数据要求为(nb_samples, input_dim)的2D张量

## 上面就处理好数据了，接下来开始创建模型

In [4]:
# 创建模型
model = Sequential([
    Dense(units=10, input_dim=784, bias_initializer="one", activation="softmax")
])

# 定义优化器，编译模型。一定要注意optimizer别写成Optimizer或optimizers噢噢噢噢
sgd = SGD(lr=0.2)
model.compile(optimizer=sgd, loss="mse", metrics= ['accuracy']) 

# 开始训练模型
model.fit(x_train, y_train, epochs=10, batch_size=32)

# 评估模型
loss, accuracy = model.evaluate(x_test, y_test)
print("loss:", loss)
print('accuracy:', accuracy)

/usr/local/lib/python3.7/dist-packages/keras/optimizers/optimizer_v2/gradient_descent.py:108: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


Epoch 1/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0373 - accuracy: 0.7767
Epoch 2/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0202 - accuracy: 0.8816
Epoch 3/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0177 - accuracy: 0.8928
Epoch 4/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0164 - accuracy: 0.8994
Epoch 5/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0156 - accuracy: 0.9034
Epoch 6/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0151 - accuracy: 0.9061
Epoch 7/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0146 - accuracy: 0.9087
Epoch 8/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0143 - accuracy: 0.9105
Epoch 9/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0140 - accuracy: 0.9125
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 0.0130 

In [7]:
{i: v for i, v in enumerate(model.layers)}

{0: <keras.layers.core.dense.Dense at 0x7f27312fe550>}